In [1]:
#np.sort  👉It returns a sorted copy of an array (doesn’t change the original array).
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[74, 37, 68, 27],
       [23, 98, 58, 74],
       [ 9, 32, 45, 87],
       [70, 17, 22, 19],
       [14, 72, 66, 69],
       [87, 90, 13, 60]])

In [3]:
np.sort(a)

array([ 5,  5, 21, 31, 37, 39, 39, 44, 47, 53, 80, 91, 93, 95, 96])

In [6]:
#for descending order sorting 
np.sort(a)[::-1]

array([96, 95, 93, 91, 80, 53, 47, 44, 39, 39, 37, 31, 21,  5,  5])

In [4]:
np.sort(b) #row-wise sorting happen here or np.sort(b, axis = 1)

array([[27, 37, 68, 74],
       [23, 58, 74, 98],
       [ 9, 32, 45, 87],
       [17, 19, 22, 70],
       [14, 66, 69, 72],
       [13, 60, 87, 90]])

In [5]:
np.sort(b, axis=0) #column-wise sorting happen here

array([[ 9, 17, 13, 19],
       [14, 32, 22, 27],
       [23, 37, 45, 60],
       [70, 72, 58, 69],
       [74, 90, 66, 74],
       [87, 98, 68, 87]])

In [7]:
#np.append 👉It adds values to end of an array and returns a new array (original array stays unchanged).
a


array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [8]:
np.append(a,120)

array([  5,  47,  39,  96,  39,  80,  53,  44,  95,  37,   5,  21,  91,
        93,  31, 120])

In [9]:
b

array([[74, 37, 68, 27],
       [23, 98, 58, 74],
       [ 9, 32, 45, 87],
       [70, 17, 22, 19],
       [14, 72, 66, 69],
       [87, 90, 13, 60]])

In [10]:
np.append(b,np.ones((b.shape[0],1)),axis=1)  #This is often used to add a bias column (intercept term) in machine learning models.

array([[74., 37., 68., 27.,  1.],
       [23., 98., 58., 74.,  1.],
       [ 9., 32., 45., 87.,  1.],
       [70., 17., 22., 19.,  1.],
       [14., 72., 66., 69.,  1.],
       [87., 90., 13., 60.,  1.]])

In [12]:
#np.concatenate → It joins multiple arrays together along a specified axis.
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


Key point:
axis=0 → stack rows (vertical)
axis=1 → stack columns (horizontal)

In [13]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [16]:
#np.unique -> np.unique returns sorted unique elements of an array (removes duplicates)

e = np.array([1,2,2,2,2,3,4,5,5,6,6,6,7,7,7,10])
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [20]:
#np.expand_dims It adds a new axis (dimension) to an array at a specified position.
#It’s often used when you need to match dimensions for ML models or broadcasting.
a.shape

(15,)

In [22]:
np.expand_dims(a, axis = 0).shape

(1, 15)

In [21]:
np.expand_dims(a, axis = 1).shape

(15, 1)

In [ ]:
#np.where → It returns elements based on a condition (like an if-else for arrays).
#Key idea:
#1.Works like vectorized if-else
#2.Can also be used to find positions (indices)

In [23]:
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [24]:
#find index position of numbers whose value > 50
np.where(a>50)

(array([ 3,  5,  6,  8, 12, 13], dtype=int64),)

In [25]:
#replace all values greater than 50 with 0 , np.where(condition, true, false)
np.where(a>50,0,a)

array([ 5, 47, 39,  0, 39,  0,  0, 44,  0, 37,  5, 21,  0,  0, 31])

In [26]:
#replace all even numbers with 0
np.where(a%2==0 , 0 , a)

array([ 5, 47, 39,  0, 39,  0, 53,  0, 95, 37,  5, 21, 91, 93, 31])

In [27]:
#np.argmax → It returns the index of the maximum value in an array.
a


array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [28]:
np.argmax(a)

3

In [29]:
b

array([[74, 37, 68, 27],
       [23, 98, 58, 74],
       [ 9, 32, 45, 87],
       [70, 17, 22, 19],
       [14, 72, 66, 69],
       [87, 90, 13, 60]])

In [31]:
np.argmax(b, axis=0) #column-wise

array([5, 1, 0, 2], dtype=int64)

In [33]:
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [32]:
np.argmin(a)

0

In [34]:
#np.cumsum gives the sum of elements step-by-step.
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [35]:
np.cumsum(a)

array([  5,  52,  91, 187, 226, 306, 359, 403, 498, 535, 540, 561, 652,
       745, 776])

In [36]:
b

array([[74, 37, 68, 27],
       [23, 98, 58, 74],
       [ 9, 32, 45, 87],
       [70, 17, 22, 19],
       [14, 72, 66, 69],
       [87, 90, 13, 60]])

In [38]:
np.cumsum(b, axis = 0) #col-wise

array([[ 74,  37,  68,  27],
       [ 97, 135, 126, 101],
       [106, 167, 171, 188],
       [176, 184, 193, 207],
       [190, 256, 259, 276],
       [277, 346, 272, 336]])

In [39]:
np.cumsum(b, axis = 1) #row-wise

array([[ 74, 111, 179, 206],
       [ 23, 121, 179, 253],
       [  9,  41,  86, 173],
       [ 70,  87, 109, 128],
       [ 14,  86, 152, 221],
       [ 87, 177, 190, 250]])

In [40]:
#np.cumprod It returns the running product (cumulative multiplication) of array elements.
np.cumprod(a)

array([          5,         235,        9165,      879840,    34313760,
       -1549866496,  -538545664,  2073794560,  -558012416,   828377088,
        -153081856,  1080248320,  -481650688, -1843841024, -1324496896])

In [ ]:
#uses - Used in probabilities, growth calculations, and compounded values.

In [41]:
#np.percentile
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [45]:
np.percentile(a,100)

96.0

In [46]:
#np.histogram It counts how many values fall into different ranges (bins).
a


array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [47]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([2, 5, 3, 0, 5], dtype=int64), array([  0,  20,  40,  60,  80, 100]))

In [ ]:
#np.corrcoef →It measures how strongly two variables are related.
#np.corrcoef gives the correlation between variables (from -1 to 1).

In [49]:
salary = np.array([10000, 15000, 20000, 25000])
experience = np.array([1, 3, 2, 4])
np.corrcoef(salary,experience)

array([[1. , 0.8],
       [0.8, 1. ]])

In [50]:
#np.isin  → It checks whether elements (multiple items) of one array exist in another array.
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [54]:
items = ([12,20,34,5,78,90,96,80,])
np.isin(a,items)

array([ True, False, False,  True, False,  True, False, False, False,
       False,  True, False, False, False, False])

In [55]:
a[np.isin(a,items)]

array([ 5, 96, 80,  5])

In [57]:
#np.flip (NumPy flip) → It reverses the order of elements in an array.
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [58]:
np.flip(a)

array([31, 93, 91, 21,  5, 37, 95, 44, 53, 80, 39, 96, 39, 47,  5])

In [59]:
b

array([[74, 37, 68, 27],
       [23, 98, 58, 74],
       [ 9, 32, 45, 87],
       [70, 17, 22, 19],
       [14, 72, 66, 69],
       [87, 90, 13, 60]])

In [60]:
np.flip(b) #row flipping and col flipping

array([[60, 13, 90, 87],
       [69, 66, 72, 14],
       [19, 22, 17, 70],
       [87, 45, 32,  9],
       [74, 58, 98, 23],
       [27, 68, 37, 74]])

In [61]:
np.flip(b, axis = 0) #col

array([[87, 90, 13, 60],
       [14, 72, 66, 69],
       [70, 17, 22, 19],
       [ 9, 32, 45, 87],
       [23, 98, 58, 74],
       [74, 37, 68, 27]])

In [62]:
np.flip(b, axis = 1) #row

array([[27, 68, 37, 74],
       [74, 58, 98, 23],
       [87, 45, 32,  9],
       [19, 22, 17, 70],
       [69, 66, 72, 14],
       [60, 13, 90, 87]])

In [63]:
#np.put np.put → It replaces elements in an array at specific indices. It modifies the original array (in-place)
a

array([ 5, 47, 39, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [65]:
np.put(a,[1,2], [20,30])

In [66]:
a

array([ 5, 20, 30, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [67]:
#np.delete (NumPy delete) →It removes elements from an array and returns a new array.
np.delete(a,[0])

array([20, 30, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [68]:
np.delete(a,[0,2,5])

array([20, 96, 39, 53, 44, 95, 37,  5, 21, 91, 93, 31])

#SET FUNCTIONS np.union1d, np.intersect1d, np.setdiff1d, np.setxor1d, np.in1d

In [70]:
m = np.array([1,2,4,5,6])
n = np.array([3,5,8,9,4])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [71]:
np.intersect1d(m, n)

array([4, 5])

In [72]:
np.setdiff1d(m, n)   #items in m but not in n 

array([1, 2, 6])

In [73]:
np.setxor1d(m, n)  #remove commons and keep rest

array([1, 2, 3, 6, 8, 9])

In [74]:
np.in1d(m, 4)  #np.in1d returns a boolean array showing membership of elements.

array([False, False,  True, False, False])

In [75]:
#np.clip np.clip forces values to stay between a minimum and maximum.

a

array([ 5, 20, 30, 96, 39, 80, 53, 44, 95, 37,  5, 21, 91, 93, 31])

In [76]:
np.clip(a, a_min = 25,a_max = 80)

array([25, 25, 30, 80, 39, 80, 53, 44, 80, 37, 25, 25, 80, 80, 31])

In [ ]:
#for interview prep - #np.swapaxes, np.uniform , np.repeat, np.count_nonzero, np.tile, np.allclose and equals