#NumPy is a Python library that helps you store data in arrays and do calculations efficiently.


NumPy = Fast math + arrays in Python

USES OF NUMPY - 
- Handle large datasets easily
- Perform mathematical operations quickly
- Work with multi-dimensional arrays (1D, 2D, 3D…)
- Foundation for data science & machine learning

#1 creating numpy arrays using np.array

In [1]:
#np.array
import numpy as np

In [96]:
q = np.array([1,2,3])    #we use np.array function to create an numpy array
print(q)                 

[1 2 3]


In [97]:
type(q)

numpy.ndarray

In [98]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])

In [99]:
print(b)   #b is matrix

[[1 2 3]
 [4 5 6]]


In [100]:
type(b)

numpy.ndarray

In [101]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [102]:
type(c)
print(c)          #3D array 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [103]:
#we can make numpy array of the datatype that we want.
#dtype

np.array([2,4,6], dtype=float)

array([2., 4., 6.])

In [104]:
np.array([2,4,0], dtype=bool)   #python treats everything as true except 0

array([ True,  True, False])

In [105]:
np.array([2,4,6], dtype=complex)

array([2.+0.j, 4.+0.j, 6.+0.j])

#2 creating numpy arrays using np.arange

In [106]:
d = np.arange(1, 11, 1)

In [107]:
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


In [108]:
#reshape

np.arange(1,11).reshape(5,2)    

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [109]:
#np.ones
np.ones([2,2])            #use-case : Initialize data (starting point), used in ML

array([[1., 1.],
       [1., 1.]])

In [110]:
#np.zeros
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
#np.random                 #it gives values from [0,1)
np.random.random((3,4))   #bydeafault when creating arrays in numpy, they have float dtype. random is a class inside its there is random function 

array([[0.2583329 , 0.39833241, 0.98613594, 0.87341587],
       [0.79012953, 0.67562232, 0.14652401, 0.23073715],
       [0.84572376, 0.65545041, 0.99990687, 0.86382546]])

In [112]:
#np.linspace   (linear space)
np.linspace(-10, 10, 10)   #lower range, upper range, no of items you want to generate, generate points at equal distance within the range

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [113]:
#np.identity
np.identity(3)  #identity matrix is one whose all diagonal elements are 1's rest are 0's.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#ARRAY ATTRIBUTES

In [114]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a2)
print(a3)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [45]:
#ndim   no. of dimensions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [115]:
#shape           
a1.shape

(10,)

In [116]:
a2.shape

(3, 4)

In [117]:
print(a3.shape)
a3                         #(2,2,2) there are two(2) 2-D arrays of size (2,2)

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [118]:
#size   size tells how many no of items exist in each dimension
a2.size

12

In [119]:
#itemsize    size of dtype in the array(bytes)
a3.itemsize

4

In [120]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#Changing datatypes

In [121]:
#astype
a2.astype(np.int32)     

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#Array Operations

In [122]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
#scalar operations

#arithmetic
print(a1 * 3)
print(a1 + 2)
print(a1 - 2)
print(a1 / 2)
print(a1 ** 2)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [124]:
#relational operators < , >, ==, != etc.
a2<=15

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [125]:
#vector operations - using two numpy arrays
a1 + a2   #since both has same shape .

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#Array Function

In [4]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[54., 59., 91.],
       [91., 34., 60.],
       [31., 19., 54.]])

In [5]:
#max/min/sum/prod

np.max(a1)

91.0

In [6]:
np.min(a1)

19.0

In [7]:
np.sum(a1)

493.0

In [8]:
np.prod(a1)

1711858163127840.0

In [9]:
#to find minimum from each row/col , 0->col, 1->row
np.max(a1, axis=1)

array([91., 91., 54.])

In [10]:
np.min(a1, axis = 0)

array([31., 19., 54.])

In [12]:
#mean/medin/std/variance - Statistical Operations
np.mean(a1)
np.mean(a1, axis = 1)

array([68.        , 61.66666667, 34.66666667])

In [13]:
np.median(a1)

54.0

#trignometric functions

In [14]:
np.sin(a1)

array([[-0.55878905,  0.63673801,  0.10598751],
       [ 0.10598751,  0.52908269, -0.30481062],
       [-0.40403765,  0.14987721, -0.55878905]])

#Dot Product

In [15]:
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)

In [16]:
np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#Log and exponents

In [17]:
a1

array([[54., 59., 91.],
       [91., 34., 60.],
       [31., 19., 54.]])

In [20]:
np.log(a1)
np.exp(a1)

array([[2.83075330e+23, 4.20121040e+25, 3.31740010e+39],
       [3.31740010e+39, 5.83461743e+14, 1.14200739e+26],
       [2.90488497e+13, 1.78482301e+08, 2.83075330e+23]])

#round/floor/ceil           floor sets u to back of integer like 6.9 will give 6 and for ceil viceversa

In [27]:
a5 = np.ceil(np.random.random((2,3)) * 100)
a5

array([[ 1., 51., 97.],
       [13., 18., 72.]])

#Indexing 

In [10]:
a6 = np.arange(10)
a7 = np.arange(12).reshape(3,4)
a8 = np.arange(27).reshape(3,3,3)
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
a6[4]

4

In [4]:
a6[0]   

0

In [6]:
a7[1,3]

7

In [8]:
a8[1,1,0]

6

#Slicing

In [13]:
a6[2:5]

array([2, 3, 4])

In [14]:
a6[2:5:2]

array([2, 4])

In [15]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a7[0,:]

array([0, 1, 2, 3])

In [17]:
a7[:,2]

array([ 2,  6, 10])

In [18]:
a7[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [19]:
a7[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [20]:
a7[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [21]:
a7[1,::3]

array([4, 7])

In [22]:
a7[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

#ITERATING

In [26]:
a6
for i in a6:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [27]:
a7                  #in 2-D when we use loop, for one iteration it displays 1 row.
for i in a7:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [32]:
a8                 #in 3-D when we use loop, for one iteration it displays 1 2-D array.
for i in a8:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [33]:
##in order to run loop on each item in 2-D and 3-D array , we use a func called nditer() 
##which converts any dimension array into 1-D array and then prints it.
for i in np.nditer(a8):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [41]:
#reshape
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
#ravel - it turns any dimension array into 1-D array
a7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
#transpose
print(a7)
np.transpose(a7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [38]:
#another syntax for transpose- 
a7.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
## results are visible for any function , then its a temporary operation
## if results are not visible , its permanent operation.

#STACKING usecase - when we have multiple datasources, so we bring data from various sources and stack them , we just need shape should be same.

In [45]:
#horizontal stacking
a9 = np.arange(12).reshape(3,4)
a10 = np.arange(12,24).reshape(3,4)
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
np.hstack((a9,a10))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical stacking

In [52]:
np.vstack((a9,a10))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#SPLITING - opp of stacking, when we want to split data

In [56]:
#horizontal splitting
a9
np.hsplit(a9,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [57]:
#vertical splitting
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
np.vsplit(a10,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]